### ISSUE TITLE
Knop "aanvraagformulier downloaden" 

### ISSUE THREAD

**Issue by MartijnRWS** [VCDH/assetwebsite#15]
De knop "aanvraagformulier downloaden" valt (bij google Chrome) net buiten beeld waardoor je een stukje naar beneden moet scrollen. Kan dit aangepast worden zodat dit op 1 pagina past, zonder te hoeven scrollen? Screenshot is bijgevoegd. 
[DRIP form.docx](https://github.com/VCDH/assetwebsite/files/4734900/DRIP.form.docx)

**Comment by VCDH** [comment]
Vanwege de nieuwe functie om DRIP-selecties op te slaan en later opnieuw te openen, is de knop _Aanvraagformulier downloaden_ tevens boven de tabel met DRIPs geplaatst.
